#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Python Design Pattern  # The title of the book. Will be placed in the left navbar.
author                      : Thomas Guyader  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

repository:
  url                       : https://github.com/tom333/pdp
  branch: main

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
